# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 🏹 Build and deploy Hunter Fitness API to Azure Functions

on:
  push:
    branches:
      - master
      - main  # Agregamos main también por si cambias
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'hunter-fitness-api'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './hunter_fitness_api'  # Cambiar a tu carpeta correcta
  DOTNET_VERSION: '8.0.x'  # Especificar versión completa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 🔄 Checkout GitHub Action
        uses: actions/checkout@v4

      - name: 🔧 Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4  # Actualizar a v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 Restore Project Dependencies
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          popd

      - name: 🏗️ Build Project
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --no-restore
          popd

      - name: 📋 Publish Project
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish --configuration Release --no-build --output ../output
          popd

      - name: 🔐 Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E5646C2C00794B93A71D81DC5F9E8D1F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F4990B344EB4421296FED1CE0B6E9620 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7CF3D59C721944028A9DF8BCD01A6CF5 }}

      - name: 🚀 Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './output'

      - name: ✅ Deployment Success
        run: |
          echo "🎉 Hunter Fitness API deployed successfully!"
          echo "🌐 URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
          echo "🏥 Health Check: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/health"
          echo "📊 Functions: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api"
